"""Add head_id and last_completed_date to registers

Revision ID: 897356ca9cba
Revises: k1l2m3n4o5p6
Create Date: 2026-07-11 10:17:51.764779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '897356ca9cba'
down_revision = 'k1l2m3n4o5p6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_requested_by'))
        batch_op.drop_index(batch_op.f('ix_approvals_status'))

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_category'))
        batch_op.drop_index(batch_op.f('ix_assets_created_at'))
        batch_op.drop_index(batch_op.f('ix_assets_department_id'))
        batch_op.drop_index(batch_op.f('ix_assets_status'))

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_status'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_user_id'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_purchase_order_id'))

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_created_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_department_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_status'))

    with op.batch_alter_table('recruitment_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruitments_applications_recruitment_id'))
        batch_op.drop_index(batch_op.f('ix_recruitments_applications_stage'))

    with op.batch_alter_table('recruitments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruitments_created_at'))
        batch_op.drop_index(batch_op.f('ix_recruitments_department_id'))
        batch_op.drop_index(batch_op.f('ix_recruitments_status'))

    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_completed_date', sa.Date(), nullable=True))

    with op.batch_alter_table('salary_increments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_increments_created_at'))
        batch_op.drop_index(batch_op.f('ix_salary_increments_employee_id'))
        batch_op.drop_index(batch_op.f('ix_salary_increments_status'))

    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_task_history_task_id'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('due_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_by'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_to'))
        batch_op.drop_index(batch_op.f('ix_tasks_department_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_assigned_by'), ['assigned_by'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_history_task_id'), ['task_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('salary_increments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_increments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_increments_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_increments_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.drop_column('last_completed_date')

    with op.batch_alter_table('recruitments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruitments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruitments_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruitments_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('recruitment_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruitments_applications_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruitments_applications_recruitment_id'), ['recruitment_id'], unique=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_purchase_order_id'), ['purchase_order_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_status'), ['status'], unique=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_category'), ['category'], unique=False)

    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_requested_by'), ['requested_by'], unique=False)

    # ### end Alembic commands ###
